import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProviderWrapper from "./SessionProviderWrapper";
import "./globals.css";
import HomePageWrapper from "./homePageWrapper";
import { DarkModeProvider } from "@/context/DarkModeContext";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Govinda Dahal",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/favicon.ico"
  // }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      {/* <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head> */}
      <body className={inter.className}>
        <DarkModeProvider>
          <SessionProviderWrapper>
            <HomePageWrapper>{children}</HomePageWrapper>
          </SessionProviderWrapper>
        </DarkModeProvider>
      </body>
    </html>
  )
}
